### ISSUE TITLE
Cannot update discovery servers. Empty or invalid response body

### ISSUE THREAD

**Issue by ismriv** [h2non/resilient-consul#4]
Hello, I'm trying to use [https://github.com/resilient-http/resilient.js](resilient.js) with Consul using this middleware, but I'm getting the error depicted in the title when following the example shown in the README file.

I've basically registered a service in Consul using CURL:
    curl -X PUT -d '{"Node": "my-node", "Address": "127.0.0.1", "Service": {"Service": "my-service", "Port": 49000}}' http://127.0.0.1:8500/v1/catalog/register

The above is an HTTP server that will respond with 200 Ok when requesting `/`. Below is the code I'm using with resilient.js:

```
var resilient = require('resilient');
var consul = require('resilient-consul');
var client = resilient();

client.use(consul({
  service: 'my-service',
  // discoveryService: '..', // I've tried consul, my-node, my-service - made no difference
  enableSelfRefresh: true,
  servers: [
    '127.0.0.1:8500'
  ],
  onlyHealthy: false
}));

client.get('/', function (err, res) {
  console.log('Error:', err);
  console.log('Response:', res);
});
```

And here's the output I get:

```
Error: { [Error: Cannot update discovery servers. Empty or invalid response body]
  error: 
   { [Error: Missing discovery servers. Cannot resolve the server]
     status: 1002,
     message: 'Missing discovery servers. Cannot resolve the server' },
  status: 1001,
  message: 'Cannot update discovery servers. Empty or invalid response body' }
Response: undefined
```

What am I doing wrong? Thanks in advance!

**Comment by h2non** [comment]
Seems like the Consul response is not valid, probably due to the servers has not been registered properly in the agent. Could you try with http://demo.consul.io ?

**Comment by h2non** [comment]
@ismriv You've to disable the `enableSelfRefresh` if you're not using `discoveryService` option. This is designed for self discover Consul servers dynamically, but I think you don't need it.

**Comment by ismriv** [comment]
Thanks @h2non, I've just realised I was missing the `http://` part in my Consul servers, it's now working using:

```
servers: [
    'http://127.0.0.1:8500'
]
```

Kudos for the library, you've saved me a good number of hours.
