### ISSUE TITLE
mapServersFromHealthEndpoint receives array of URLs, instead of complete response 

### ISSUE THREAD

**Issue by ismriv** [h2non/resilient-consul#7]
My application crashes from time to time due to `mapServersFromHealthEndpoint` receiving a list of URLs for the service such as `['http://my-host-one:3000', 'http://my-host-two:3000']`, whereas it should receive an array of service definition objects such as:

```
{
  "Node": {
    "Node": "my-host-one",
    "Address": "xx.xx.xx.xx",
    "CreateIndex": 65,
    "ModifyIndex": 120501
  },
  "Service": {
    "ID": "my-host-one:my-service:3000",
    "Service": "my-service",
    "Tags": null,
    "Address": "ip-172-31-24-131",
    "Port": 3000,
    "EnableTagOverride": false,
    "CreateIndex": 27226,
    "ModifyIndex": 27228
  },
  "Checks": []
}
```

The error is that `s.Service` in https://github.com/h2non/resilient-consul/blob/master/consul.js#L86 is obviously undefined. `mapServersFromCatalogEndpoint` is filtering these, which I didn't understand the first time I saw it, but I believe we shouldn't need to filter anything in these functions, but address the root cause.

The issue may be in `resilient.js` to be honest, but I don't have enough knowledge of it yet to have a clearer idea. Any suggestions?

**Comment by h2non** [comment]
The adapter should always provide an array of URL to resilient. Perhaps the response from consul has not always the same interface but it's estrange, in that case the adapter should infer the interface type and map the data accordingly.

**Comment by ismriv** [comment]
I've investigated the issue a bit more. The URL used to retrieve the service info from Consul is consistent, and so is the response. It looks like in some rare cases, the middleware function is called twice, the 1st time with the response from Consul, and the 2nd time with the response from the 1st middleware function call, which is the array of URLs meant to be passed to resilient.

**Comment by h2non** [comment]
Are you attaching the middleware function more than once? If not, there could an scenario where the first discovery fetching process fails, and then resilient retries it. The consul middleware could ignore mapping the servers if `res.data` already has the desired interface. I can provide a fix for this easily.

**Comment by ismriv** [comment]
Only attaching it once. 

Fixing it here wouldn't be too hard, but it just doesn't seem to be its responsibility. `resilient-consul` shouldn't have to deal with already parsed responses (incorrect input) being passed to it.

**Comment by ismriv** [comment]
Hi @h2non. Were you able to find the root cause? Shall we implement the quick workaround in `resilient-consul` for the time being?

**Comment by h2non** [comment]
I can't invest time on this, I'm sorry. Seems like `resilient` is triggering the middleware chain more than one time under some particular scenario. As I said, you can prevent that directly from this middleware plugin until the possible issue can be mitigated in `resilient`. Feel free to make a PR for the fix and I'll merge it asap.

From the other hand, I've plans to completely redesign `resilient` core in an inminent future since it has some bad design issues and it's hard to maintain and extend from different perspectives.
